server:
  port: ${PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

app:
  openai-key: ${OPENAI_API_KEY}
  qdrant-host: ${QDRANT_HOST:qdrant}
  qdrant-port: ${QDRANT_PORT:6334}